apiVersion: batch/v1
kind: Job
metadata:
  name: scipion-cloner-$SUBST_CLONER_ACTION
  namespace: "$SUBST_NAMESPACE"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: scipion-cloner-$SUBST_CLONER_ACTION
    spec:
      restartPolicy: Never
      containers:
      - name: cloner
        image: jhandl/scipion-cloner:latest
        imagePullPolicy: Always
        env:
        - name: CLONER_ACTION
          value: "$SUBST_CLONER_ACTION"
        - name: CLONER_REMOVE_LOCK
          value: "$SUBST_CLONER_REMOVE_LOCK"
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:

          # Onedata dataset (rsync src)
        - name: scipion-od-dataset-ro
          mountPath: "/mnt/od-dataset"

          # Volume dataset (rsync dest)
        - name: scipion-vol-dataset-rw
          mountPath: "/mnt/vol-dataset"

          # Onedata project (rsync src/dest)
        - name: scipion-od-project-rw
          mountPath: "/mnt/od-project"

          # Volume project (rsync src/dest) + store logs
        - name: scipion-vol-project-rw
          mountPath: "/mnt/vol-project"

      volumes:

       # Onedata
       # ---------------------

       - name: scipion-od-dataset-ro
         persistentVolumeClaim:
           claimName: pvc-scipion-od-dataset-$SUBST_NAMESPACE
           readOnly: true

       - name: scipion-od-project-rw
         persistentVolumeClaim:
           claimName: pvc-scipion-od-project-$SUBST_NAMESPACE

       # Auto vol provisioning
       # ---------------------

       - name: scipion-vol-dataset-rw
         persistentVolumeClaim:
           claimName: pvc-scipion-vol-dataset-$SUBST_NAMESPACE

       - name: scipion-vol-project-rw
         persistentVolumeClaim:
           claimName: pvc-scipion-vol-project-$SUBST_NAMESPACE

