image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  SCIPION_REGISTRY: "hub.cerit.io/scipion"
  SCIPION_REGISTRY_PREFIX: "${SCIPION_REGISTRY}/scipion"

stages:
  # independent - base, controller, firefox
  # post_base - master, tool
  - build_independent
  - build_post_base

before_script:
  - docker info
  - docker login -u "$SCIPION_REGISTRY_USER" -p "$SCIPION_REGISTRY_PASSWORD" "$SCIPION_REGISTRY"

.build_image:
  script: &build_image
    # build and tag the image for master branch with the string "latest"
    - |
        if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then
            RELEASE_CHANNEL=latest
        else
            RELEASE_CHANNEL=${CI_COMMIT_REF_NAME}
        fi

    - docker pull ${SCIPION_REGISTRY_PREFIX}-${IMAGE_TYPE}:${RELEASE_CHANNEL} || true
    - docker build --build-arg RELEASE_CHANNEL=${CI_COMMIT_REF_NAME} --cache-from ${SCIPION_REGISTRY_PREFIX}-${IMAGE_TYPE}:${RELEASE_CHANNEL} -t "${SCIPION_REGISTRY_PREFIX}-${IMAGE_TYPE}:${RELEASE_CHANNEL}" ${IMAGE_TYPE}-image/.

    - docker push "${SCIPION_REGISTRY_PREFIX}-${IMAGE_TYPE}:${RELEASE_CHANNEL}"

build_base:
  stage: build_independent
  resource_group: rg_scipion_independent
  variables:
    IMAGE_TYPE: base
    BUILD_STAGE: base
  script:
    *build_image
  only:
    - master
    - dev
    - gitlab-ci

build_controller:
  stage: build_independent
  resource_group: rg_scipion_independent
  variables:
    IMAGE_TYPE: controller
    BUILD_STAGE: base
  script:
    *build_image
  only:
    - master
    - dev
    - gitlab-ci

build_firefox:
  stage: build_independent
  resource_group: rg_scipion_independent
  variables:
    IMAGE_TYPE: firefox
    BUILD_STAGE: base
  script:
    *build_image
  only:
    - master
    - dev
    - gitlab-ci

build_master:
  stage: build_post_base
  resource_group: rg_scipion_post_base
  variables:
    IMAGE_TYPE: master
    BUILD_STAGE: base
  script:
    *build_image
  only:
    - master
    - dev
    - gitlab-ci

build_tool:
  stage: build_post_base
  resource_group: rg_scipion_post_base
  variables:
    IMAGE_TYPE: tool
    BUILD_STAGE: base
  script:
    *build_image
  only:
    - master
    - dev
    - gitlab-ci

