image: docker:latest

services:
  - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build_base_image
  - build_node_image

build_base_image_master:
  stage: build_base_image
  script:
    - cd base-image && docker build --pull -t "${CI_REGISTRY_IMAGE}-base-image:$CI_COMMIT_REF_NAME" .
    - cd base-image && docker build --pull -t "${CI_REGISTRY_IMAGE}-base-image:latest" .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "${CI_REGISTRY_IMAGE}-base-image:$CI_COMMIT_REF_NAME"
    - docker push "${CI_REGISTRY_IMAGE}-base-image:latest"
  only:
    - master

build_base_image_dev:
  stage: build_base_image
  script:
    - cd base-image && docker build --pull -t "${CI_REGISTRY_IMAGE}-base-image:$CI_COMMIT_REF_NAME" .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "${CI_REGISTRY_IMAGE}-base-image:$CI_COMMIT_REF_NAME"
  only:
    - dev

build_master_node_master:
  stage: build_node_image
  script:
    - cd master-node && sed -i -E 's/^FROM\s+(.+):.+$/FROM \1:master/' Dockerfile
    - cd master-node && echo "$PRIV_KEY" > self.pem
    - cd master-node && docker build --pull -t "${CI_REGISTRY_IMAGE}-master-node:$CI_COMMIT_REF_NAME" .
    - cd master-node && docker build --pull -t "${CI_REGISTRY_IMAGE}-master-node:latest" .
    - docker push "${CI_REGISTRY_IMAGE}-master-node:$CI_COMMIT_REF_NAME"
    - docker push "${CI_REGISTRY_IMAGE}-master-node:latest"
  only:
    - master

build_master_node_dev:
  stage: build_node_image
  script:
    - cd master-node && sed -i -E 's/^FROM\s+(.+):.+$/FROM \1:dev/' Dockerfile
    - cd master-node && echo "$PRIV_KEY" > self.pem
    - cd master-node && docker build --pull -t "${CI_REGISTRY_IMAGE}-master-node:$CI_COMMIT_REF_NAME" .
    - docker push "${CI_REGISTRY_IMAGE}-master-node:$CI_COMMIT_REF_NAME"
  only:
    - dev

build_worker_node_master:
  stage: build_node_image
  script:
    - cd worker-node && sed -i -E 's/^FROM\s+(.+):.+$/FROM \1:master/' Dockerfile
    - cd worker-node && docker build --pull -t "${CI_REGISTRY_IMAGE}-worker-node:$CI_COMMIT_REF_NAME" .
    - cd worker-node && docker build --pull -t "${CI_REGISTRY_IMAGE}-worker-node:latest" .
    - docker push "${CI_REGISTRY_IMAGE}-worker-node:$CI_COMMIT_REF_NAME"
    - docker push "${CI_REGISTRY_IMAGE}-worker-node:latest"
  only:
    - master

build_worker_node_dev:
  stage: build_node_image
  script:
    - cd worker-node && sed -i -E 's/^FROM\s+(.+):.+$/FROM \1:dev/' Dockerfile
    - cd worker-node && docker build --pull -t "${CI_REGISTRY_IMAGE}-worker-node:$CI_COMMIT_REF_NAME" .
    - docker push "${CI_REGISTRY_IMAGE}-worker-node:$CI_COMMIT_REF_NAME"
  only:
    - dev

