#!/bin/sh

set -e

DISPLAY=:1 xhost +

dir_dataset="/mnt/vol-dataset"
dir_project="/mnt/vol-project"
dir_scipion="${dir_project}/scipion-docker"
file_status="${dir_scipion}/instance-status"
file_log="${dir_scipion}/instance.log"

# Opens xterm with a tail the logs. Is is useful before running the desktop environment
while true; do
	xterm -bg black -fg gray -fa 'Monospace' -fs 11 -maximized -xrm 'XTerm.vt100.allowTitleOps: false' -T "Instance logs" -e /bin/bash -c "while true; do ls ${file_log} > /dev/null; cat ${file_log}; sleep 10; clear; done"
done &

# Wait for the cloners ("clone" - clone dataset data, "restore" - restore project)
while [ ! -f "${file_status}" ] || ! grep -q "ok" "${file_status}"; do
	sleep 10
done

# Disable screensaver
#xset s off -dpms

# Start xfce4
echo "Starting the desktop environment" >> "${file_log}"
cd ${S_USER_HOME}
xfce4-session &

# minimize the xterm
sleep 1
xdotool getactivewindow windowminimize || true
