name: Build image

inputs:
  node_type:
    description: base-image / master-image / worker-image
    required: true
  build_stage:
    description: base / node
    required: true
  branch:
    description: Inherit branch name from workflow
    required: true

runs:
  using: "composite"
  steps:
  - name: Replace tag for a base image with branch name
    if: ${{ inputs.build_stage = "node" }}
    run: sed -i -E "s/^FROM\s+(.+):.+$/FROM \1:${{ inputs.branch }}/" ${{ inputs.node_type }}/Dockerfile

  - name: Add priv key for the MN
    if: ${{ inputs.node_type = "master-image" }}
    run: echo "$PRIV_KEY" > master-image/self.pem;

  - name: Build and push the base-image / MN-image / WN-image
    # TODO cache
    # docker pull ${CI_REGISTRY_IMAGE}/${NODE_TYPE}:${CI_COMMIT_REF_NAME} || true
    # docker build --cache-from ${CI_REGISTRY_IMAGE}/${NODE_TYPE}:${CI_COMMIT_REF_NAME} -t "${CI_REGISTRY_IMAGE}/${NODE_TYPE}:${CI_COMMIT_REF_NAME}" ${NODE_TYPE}/.

    uses: docker/build-push-action@v2
    with:
      context: ${{ inputs.node_type }}/.
      push: true
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/scipion-docker/${{ inputs.node_type }}:${{ inputs.branch }}

  - name: Build and tag the image for master branch also with the string "latest"
    if: ${{ inputs.branch = "master" }}
    uses: docker/build-push-action@v2
    with:
      context: ${{ inputs.node_type }}/.
      push: true
      pull: true
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/scipion-docker/${{ inputs.node_type }}:latest

