name: Build image

inputs:
  node_type:
    description: scipion-base / scipion-master / scipion-worker
    required: true
  build_stage:
    description: base / node
    required: true
  branch:
    description: Inherit branch name from workflow
    required: true
  dockerhub_username:
    description: DockerHub username
    required: false
    default: ceritsc

runs:
  using: "composite"
  steps:
  - name: Replace tag for a base image with branch name
    shell: bash
    run: |
            echo ${{ inputs.build_stage }}
            if [ ${{ inputs.build_stage }} = 'node' ]; then
                echo "Debug info: sed"

                sed -i -E "s/^FROM\s+(.+):.+$/FROM \1:${{ inputs.branch }}/" ${{ inputs.node_type }}/Dockerfile
            fi

  - name: Add priv key for the MN
    shell: bash
    run: |
            if [ ${{ inputs.node_type }} = 'scipion-master' ]; then
                echo "Debug info: priv key"

                echo "$PRIV_KEY" > master-image/self.pem;
            fi

  - name: Build and push the base-image / MN-image / WN-image
    shell: bash
    run: |
            IMAGE_TAG=${{ inputs.dockerhub_username }}/${{ inputs.node_type }}:${{ inputs.branch }}
            
            docker pull $IMAGE_TAG || true
            docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG ${{ inputs.node_type }}/.
            docker push $IMAGE_TAG

    # TODO cache
    # docker pull ${CI_REGISTRY_IMAGE}/${NODE_TYPE}:${CI_COMMIT_REF_NAME} || true
    # docker build --cache-from ${CI_REGISTRY_IMAGE}/${NODE_TYPE}:${CI_COMMIT_REF_NAME} -t "${CI_REGISTRY_IMAGE}/${NODE_TYPE}:${CI_COMMIT_REF_NAME}" ${NODE_TYPE}/.

    #    uses: docker/build-push-action@v2
    #    with:
    #      context: ${{ inputs.node_type }}/.
    #      push: true
    #      tags: ${{ secrets.DOCKERHUB_USERNAME }}/scipion-docker/${{ inputs.node_type }}:${{ inputs.branch }}

  - name: Build and tag the image for master branch also with the string "latest"
    shell: bash
    run: |
           if [ ${{ inputs.branch }} = 'master' ]; then
               echo "Debug info: master branch"

               IMAGE_TAG=${{ inputs.dockerhub_username }}/${{ inputs.node_type }}:latest

               docker build --pull -t $IMAGE_TAG ${{ inputs.node_type }}/.
               docker push $IMAGE_TAG
           fi

    #if: inputs.branch == 'master'
    #uses: docker/build-push-action@v2
    #with:
    #  context: ${{ inputs.node_type }}/.
    #  push: true
    #  pull: true
    #  tags: ${{ secrets.DOCKERHUB_USERNAME }}/scipion-docker/${{ inputs.node_type }}:latest

