apiVersion: v1
kind: Service
metadata:
  name: scipion-master-svc-vnc
  namespace: "$SUBST_NAMESPACE"
spec:
  type: ClusterIP
  ports:
  - name: scipion-master-port                                                 
    port: 5901
    targetPort: 5901
  selector:
    app: scipion-master
