apiVersion: apps/v1
kind: Deployment
metadata:
  name: scipion-master
  namespace: handl-ns
spec:
  selector:
    matchLabels:
      app: scipion-master
  replicas: 1
  template:
    metadata:
      labels:
        app: scipion-master
    spec:
      containers:
# Conatiner that removes old tool containers
#      - name: garbage-collector
#        image: jhandl/scipion-gc:latest
#        imagePullPolicy: Always
#        securityContext:
#          privileged: false
#          runAsUser: 1000
#          runAsGroup: 1000
      - name: scipion-master
        image: jhandl/scipion-mn:tool
        imagePullPolicy: Always
        ports:
        - containerPort: 5906
        env:
        - name: ROOT_PASS
          value: "abc"
        - name: USER_PASS
          value: "abc"
        - name: USE_DISPLAY
          value: "6"
        volumeMounts:
#        - name: x-socket
#          mountPath: /tmp/.X11-unix/X0
#        - name: scipion-user-data
#          mountPath: /home/scipionuser/ScipionUserData
        - mountPath: "/home/scipionuser/ScipionUserData"
          name: scipion-user-data
#        resources:
#          limits:
#            nvidia.com/gpu: 1 # dedicated GPU
#            cerit.io/gpu-mem: 1 # shared GPU
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
      serviceAccountName: pod-reader-sa
      volumes:
#      - name: x-socket
#        hostPath:
#          path: /tmp/.X11-unix/X0
#      - name: scipion-user-data
#        hostPath:
#          path: /home/jhandl/k8s-volume
##        emptyDir: {}
       - name: scipion-user-data
         persistentVolumeClaim:
           claimName: scipion-test-volume
