apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scipion-od-source-$SUBST_NAMESPACE
  namespace: "$SUBST_NAMESPACE"
spec:
  accessModes:
    - ReadOnlyMany # RO
  capacity:
    storage: 5000Gi
  storageClassName: "onedata"
  csi:
    driver: csi-onedata
    nodePublishSecretRef:
      name: scipion-od-source-$SUBST_NAMESPACE
      namespace: "$SUBST_NAMESPACE"
    volumeHandle: pv-scipion-od-source-$SUBST_NAMESPACE
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scipion-od-project-$SUBST_NAMESPACE
  namespace: "$SUBST_NAMESPACE"
spec:
  accessModes:
    - ReadWriteMany # RW
  capacity:
    storage: 5000Gi
  storageClassName: "onedata"
  csi:
    driver: csi-onedata
    nodePublishSecretRef:
      name: scipion-od-project-$SUBST_NAMESPACE
      namespace: "$SUBST_NAMESPACE"
    volumeHandle: pv-scipion-od-project-$SUBST_NAMESPACE
