apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-onedata-sources
  namespace: "$SUBST_NAMESPACE"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: "onedata"
  volumeName: pv-scipion-onedata-sources
