apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jhandl-onedata-test
  namespace: "$SUBST_NAMESPACE"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: "onedata"
  volumeName: pv-jhandl-onedata-test
