apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-onedata-projects
  namespace: "$SUBST_NAMESPACE"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: nfs-csi
