apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: handl-ns
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
  #  verbs: ["get", "watch", "list"]

- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
