apiVersion: v1
kind: Secret
metadata:
  name: scipion-od-source-$SUBST_NAMESPACE
  namespace: "$SUBST_NAMESPACE"
  labels:
    cerit-onedata-secret: "yes"
data:
  host: "$SUBST_OD_HOST" # host in base64 form
  onedata_token: "$SUBST_OD_SOURCE_TOKEN" # token in base64 form
  space_id: "$SUBST_OD_SOURCE_SPACE_ID" # space-id in base64 form
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: scipion-od-project-$SUBST_NAMESPACE
  namespace: "$SUBST_NAMESPACE"
  labels:
    cerit-onedata-secret: "yes"
data:
  host: "$SUBST_OD_HOST" # host in base64 form
  onedata_token: "$SUBST_OD_PROJECT_TOKEN" # token in base64 form
  space_id: "$SUBST_OD_PROJECT_SPACE_ID" # space-id in base64 form
type: Opaque
