kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: scipion-volume
    namespace: handl-ns
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: myvolume
    resources:
        requests:
            storage: 1Gi

