#!/bin/sh

notify-send --icon /opt/firefox/logo.png "Container with the Firefox will start in a few seconds"

helm template \
    --set instance.namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) \
    --set instance.name="$INSTANCE_NAME" \
    --set instance.release_channel="$RELEASE_CHANNEL" \
    --set firefox.args="$@" \
    --set od.sid.dataset="$OD_DATASET_SPACEID" \
    --set od.sid.project="$OD_PROJECT_SPACEID" \
/opt/kubernetes/chart-firefox/ | kubectl apply -f -

