name: Docker Build template

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: hub.cerit.io
          username: ${{ secrets.HUBCERIT_USERNAME }}
          password: ${{ secrets.HUBCERIT_SECRET }}

      - name: Build and push docker image
        run: ./build.sh ${{ inputs.tag }} ${{ inputs.image-name }}

      - name: Clean up
        run: docker rmi -f ${{ inputs.tag }} ${{ inputs.image-name }}
