name: Docker Image CI

on:
  push:
    branches: [ master, dev, build-action ]
  pull_request:
    branches: [ master, dev, build-action ]

jobs:

  build-base-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - run: ls -la . && pwd
    - run: ls -la .github/
    - run: tree .
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Run build action
      uses: ./.github/actions/build-action
      with:
        node_type: base-image
        build_stage: base
        branch: ${{ github.ref }}

  build-master-image:
    needs: build-base-image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run build action
      uses: ./.github/actions/build-action
      with:
        node_type: master-image
        build_stage: node
        branch: ${{ github.ref }}

  build-worker-image:
    needs: build-base-image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run build action
      uses: ./.github/actions/build-action
      with:
        node_type: worker-image
        build_stage: node
        branch: ${{ github.ref }}

